spring:
  datasource:
    url: jdbc:mysql://localhost:3306/w?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: wjx123
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true
    encoding: UTF-8
    servlet:
      content-type: text/html

# mybatis
mybatis:
  # mapper路径
  type-aliases-package: com.wangjx.spider4ajk.model
  mapper-locations: classpath:**/mapper/*.xml
server:
  port: 9300
